### ISSUE TITLE
MENU_TIMEOUT="0" does not work to set the ipxe boot menu to show up forever

### ISSUE THREAD

**Issue by jphein** [ltsp/ltsp#69] opened 2019-11-14 04:01 UTC
I tried: 
[clients]
MENU_TIMEOUT="-1"

[clients]
MENU_TIMEOUT="0"

[server]
MENU_TIMEOUT="0"

[server]
MENU_TIMEOUT="-1"

`ltsp ipxe`
`ltsp initrd`

**Comment by jphein** [comment] 2019-11-14 04:01
MAN says:

MENU_TIMEOUT=“5000”
These parameters can be defined under [mac:address] sections in ltsp.conf, and they are used by ltsp ipxe to generate the iPXE menu. They control the default menu item, the additional kernel parameters and the menu timeout for each client. MENU_TIMEOUT can also be defined globally under [clients].

**Comment by alkisg** [comment] 2019-11-14 05:26
Set:

```shell
[common]
MENU_TIMEOUT=0
```

Then run:

```shell
sudo ltsp ipxe
grep menu-timeout /srv/tftp/ltsp/ltsp.ipxe
```

And upload the output. I think there's a bug concerning the "under [clients]" phrase, but let's make sure that it works like I described above first.

**Comment by jphein** [comment] 2019-11-14 05:34
```
grep menu-timeout /srv/tftp/ltsp/ltsp.ipxe
# MENU_TIMEOUT (menu-timeout): menu milliseconds, 0=forever, -1=hide menu
# To completely hide the menu, set menu-timeout to -1
isset ${menu-timeout} || set menu-timeout 5000
iseq "${menu-timeout}" "-1" && goto ${img} ||
choose --timeout ${menu-timeout} --default ${img} img || goto cancel

```

**Comment by jphein** [comment] 2019-11-14 05:35
```
grep menu-timeout /srv/tftp/ltsp/ltsp.ipxe
# MENU_TIMEOUT (menu-timeout): menu milliseconds, 0=forever, -1=hide menu
# To completely hide the menu, set menu-timeout to -1
isset ${menu-timeout} || set menu-timeout -1
iseq "${menu-timeout}" "-1" && goto ${img} ||
choose --timeout ${menu-timeout} --default ${img} img || goto cancel

```
tried again, but this time set to -1

**Comment by jphein** [comment] 2019-11-14 05:36
weird it worked the second time

**Comment by jphein** [comment] 2019-11-14 05:39
Yeah, only works with -1. Which is fine for me. That's all I need.
Thank you!

**Comment by alkisg** [comment] 2019-11-14 05:40
Jeffrey, could you please summarize which part needs fixing?

0 doesn't work, and "under [clients]" is wrong?

**Comment by jphein** [comment] 2019-11-14 05:44
ahhh, sorry.
MENU_TIMEOUT="-1" is for hiding the menu. 
MENU_TIMEOUT="0" is for having the menu show up indefinitely.  
My mistake.

However neither of them work in the [clients] section. 
MENU_TIMEOUT="-1" does work in the [common] section. 
That would just be a documentation change. 

However if we wanted to support the iPXE menu to show up indefinitely. We should add MENU_TIMEOUT="0" as an option in [common]

**Comment by alkisg** [comment] 2019-11-14 06:21
> However if we wanted to support the iPXE menu to show up indefinitely. We should add MENU_TIMEOUT="0" as an option in [common]

Doesn't that work already?

**Comment by jphein** [comment] 2019-11-15 21:01
You're right id does! O_O
lol, must have been my mistake with the test. 
Closing issue.

**Comment by jphein** [comment] 2019-11-15 21:02
WAIT! No that does not work. Reopening.

**Comment by jphein** [comment] 2019-11-15 21:06
The only one that works actually is:

[common]
MENU_TIMEOUT="-1"

All others like
[common]
MENU_TIMEOUT="300"
do not work for me

**Comment by jphein** [comment] 2019-11-15 21:08
hmmmm.... commenting it out.
#MENU_TIMEOUT="-1"

doesn't bring it back to the default of 5000 anymore.
Maybe it's my installation.

**Comment by jphein** [comment] 2019-11-15 21:12
OK, I've tested other Timeout values.

[common]
MENU_TIMEOUT="0"

[common]
MENU_TIMEOUT="-1"

[common]
MENU_TIMEOUT="500"

[common]
MENU_TIMEOUT="30000"

The only ones that does not work is:
[common]
MENU_TIMEOUT="0"

**Comment by alkisg** [comment] 2019-11-16 03:40
So, when you specify MENU_TIMEOUT=0, does the following line get properly set in ltsp.ipxe?

```shell
isset ${menu-timeout} || set menu-timeout 0
```

If so, AFAIK then ipxe just waits indefinitely, without using a timeout: https://ipxe.org/cmd/choose

**Comment by jphein** [comment] 2019-11-16 05:16
No. It does not.
```
cat /etc/ltsp/ltsp.conf 
...
[common]
MENU_TIMEOUT="0"
...
```
```
sudo ltsp  ipxe
Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipped existing /srv/tftp/ltsp/memtest.0
Skipped existing /srv/tftp/ltsp/memtest.efi
Skipped existing /srv/tftp/ltsp/snponly.efi
Skipped existing /srv/tftp/ltsp/undionly.kpxe
```
```
grep menu-timeout /srv/tftp/ltsp/ltsp.ipxe
# MENU_TIMEOUT (menu-timeout): menu milliseconds, 0=forever, -1=hide menu
# To completely hide the menu, set menu-timeout to -1
isset ${menu-timeout} || set menu-timeout 5000
iseq "${menu-timeout}" "-1" && goto ${img} ||
choose --timeout ${menu-timeout} --default ${img} img || goto cancel
```

**Comment by alkisg** [comment] 2019-11-16 05:27
You're right, the problem is in our [textif() function](https://github.com/ltsp/ltsp/blob/master/ltsp/common/ltsp/55-config.sh#L312), it special-cases zero for cases like e.g. DNS=0 (to avoid any modifications there), while for ipxe zero shouldn't be special-cased.

Ty, will fix shortly.

**Comment by alkisg** [comment] 2019-11-16 06:01
Thanks, fix committed in https://github.com/ltsp/ltsp/commit/398b889f85af3f3d7a55d3cd385448339b40e05d.

Please test using the [LTSP proposed PPA](https://ltsp.github.io/advanced/proposed-ppa/).

**Closed by alkisg** 2019-11-16 06:01 UTC
