### ISSUE TITLE
Bogus error message on the client. The image is too big.

### ISSUE THREAD

**Issue by rkwesk** [ltsp/ltsp#23] opened 2019-09-04 21:28 UTC
I will return here with more details. For now I want to report that I attempted to install ltsp19 on a laptop that was not the same as the one I reported as another success. I tried the install three times and only when I start the client is the error reported. The install seemed to go alright up until starting the client.

I will return to this issue with more details in a few days.

Richard

**Comment by alkisg** [comment] 2019-09-05 02:55
I think this is a duplicate of issue #21, see https://github.com/ltsp/ltsp/issues/21#issuecomment-527212422

**Closed by alkisg** 2019-09-05 02:55 UTC
