### ISSUE TITLE
'ltsp image /' should work with advanced partitioning

### ISSUE THREAD

**Issue by schweer-guest** [ltsp/ltsp#105] opened 2019-12-07 20:56 UTC
While Trying to integrate the new LTSP into Debian Edu I noticed that the 'ltsp image /' command didn't work like expected. The reason seems to be the used disk partitioning that hadn't been 'atomic' (Debian speak for 'all files in one partition'):

Content of /etc/fstab
/dev/mapper/vg_system-root / ext4 errors=remount-ro 0 1
UUID=b0912e9f-aa81-42bf-b056-63bf9c0e4ff1 /boot ext4 defaults 0 2
/dev/mapper/vg_system-usr /usr ext4 defaults 0 2
/dev/mapper/vg_system-swap_1 none swap sw 0 0
/dev/sr0 /media/cdrom0 udf,iso9660 user,noauto 0 0

Used tool: setup_debian_edu_ltsp, see:
https://lists.debian.org/debian-edu/2019/12/msg00006.html

I ran './setup_debian_edu_ltsp amd64 testing no'  (only amd64 thin client, ok)
and then './setup_debian_edu_ltsp amd64'            (diskless workstation)
which resulted in /srv/ltsp/images/x86_64.img with empty /boot and /usr dirs
(and so unable to copy initrd and vmlinuz because of missing /boot dir).

To fix /srv/ltsp/images/x86_64.img I did this:
rm /srv/ltsp/images/x86_64.img
mksquashfs /usr /srv/ltsp/images/x86_64.img -wildcards -ef /usr/share/ltsp/server/image/image.excludes
mksquashfs /boot /srv/ltsp/images/x86_64.img -wildcards -ef /usr/share/ltsp/server/image/image.excludes
mksquashfs / /srv/ltsp/images/x86_64.img -wildcards -ef /usr/share/ltsp/server/image/image.excludes
ltsp kernel
ltsp ipxe
./setup_debian_edu_ltsp amd64 testing no (to edit the ipxe menu)

Despite some strange links in the root dir of /srv/ltsp/images/x86_64.img, which could most probably be avoided via excludes, the Diskless Workstation came up expected, login was ok. 

Turning a workstation that had been partitioned manually (type 'atomic') into an LTSP server is working without issues, but I figure it would be good if other partitioning than just 'atomic' could be supported. I don't know enough about SquashFS, the new LTSP and coding to come up with a fix, though.

Wolfgang

**Comment by alkisg** [comment] 2019-12-07 21:28
Hi Wolfgang,

I believe this is a duplicate of issue #43.
Unfortunately the workaround that I mention there for /boot won't work for you, as /usr is too big to copy around.
I hope I'll have enough time to fix it for Ubuntu 20.04 and certainly for Bullseye.

**Closed** 2019-12-08 06:44 UTC
