### ISSUE TITLE
cannot create image on Ubuntu 16.04

### ISSUE THREAD

**Issue by enoch85** [ltsp/ltsp#62] opened 2019-11-04 15:30 UTC
```
root@thinclient01:/srv/tftp/ltsp/x86_32# ltsp info
LTSP version: 19.10-1~201911020603~ubuntu16.04.1

SERVER XSESSIONS: Lubuntu.desktop  Lubuntu-Netbook.desktop  openbox.desktop

SERVER OS: PRETTY_NAME="Ubuntu 16.04.6 LTS"

CHROOTS:


VMs:


IMAGES:
x86_32
```

Running `ltsp image /` for chrootless results in:

```
root@thinclient01:~# ltsp image /
Using x86_32 as the base name of image /
Running: mount --bind --make-private -o ro / /tmp/tmp.F6KHlqXNTT/root/
Trying to acquire package management lock: //var/lib/dpkg/lock
Running: mount -t overlay -o upperdir=/tmp/tmp.F6KHlqXNTT/tmpfs/up,lowerdir=/tmp/tmp.F6KHlqXNTT/root,workdir=/tmp/tmp.F6KHlqXNTT/tmpfs/work /tmp/tmp.F6KHlqXNTT/tmpfs /tmp/tmp.F6KHlqXNTT/root
Cleaning up x86_32 before mksquashfs...
Replacing /tmp/tmp.F6KHlqXNTT/root/etc/ssh/ssh_host_dsa_key
Replacing /tmp/tmp.F6KHlqXNTT/root/etc/ssh/ssh_host_ecdsa_key
Replacing /tmp/tmp.F6KHlqXNTT/root/etc/ssh/ssh_host_ed25519_key
Replacing /tmp/tmp.F6KHlqXNTT/root/etc/ssh/ssh_host_rsa_key
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on /srv/ltsp/images/x86_32.img.tmp, block size 131072.
[====================================================================================================================================================================-] 126122/126122 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 1113243.10 Kbytes (1087.15 Mbytes)
	39.32% of uncompressed filesystem size (2831307.64 Kbytes)
Inode table size 1625902 bytes (1587.79 Kbytes)
	27.30% of uncompressed inode table size (5956599 bytes)
Directory table size 1641303 bytes (1602.83 Kbytes)
	41.20% of uncompressed directory table size (3983816 bytes)
Xattr table size 52 bytes (0.05 Kbytes)
	32.50% of uncompressed xattr table size (160 bytes)
Number of duplicate files found 27597
Number of inodes 170621
Number of files 126350
Number of fragments 6970
Number of symbolic links  23221
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 21050
Number of ids (unique uids + gids) 23
Number of uids 8
	root (0)
	_apt (105)
	man (6)
	statd (115)
	lightdm (108)
	administrator (1000)
	ntp (109)
	syslog (104)
Number of gids 18
	root (0)
	dip (30)
	shadow (42)
	dialout (20)
	tty (5)
	crontab (107)
	mlocate (116)
	utmp (43)
	ssh (117)
	messagebus (110)
	mail (8)
	staff (50)
	whoopsie (115)
	syslog (108)
	lightdm (112)
	nogroup (65534)
	ntp (114)
	adm (4)
Running: ltsp kernel /srv/ltsp/images/x86_32.img
Running:  mount -t squashfs -o ro /srv/ltsp/images/x86_32.img /tmp/tmp.WHOpeTyfFW/ltsp/
Could not locate vmlinuz and initrd.img in /srv/ltsp/images/x86_32.img
```

It seems to me that the tmp destination is changed, but I might be wrong. Also there are double `//` on this row: `Trying to acquire package management lock: //var/lib/dpkg/lock` I don't know if that has any impact?

**Comment by alkisg** [comment] 2019-11-04 16:07
Hi Danial, this is a duplicate of #43, closing from here, let's continue there!

**Closed by alkisg** 2019-11-04 16:07 UTC
