### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by wforumw** [ltsp/ltsp#26] opened 2019-09-13 12:23 UTC
Hi,
I try to setup the new LTSP19. We have a server (Debian Buster) with a working LDAP authentication. Now I install LTSP19 (following https://github.com/ltsp/ltsp/wiki/installation) on our server. We use the Chrootless environment.
When a client boots it stops at

> Could not configure PAM for SSH authentication!
LTSP command failed: /usr/share/ltsp/client/login/pamltsp install

Is LDAP authentication working or what do we have to do to get it working?
Or is it only working in a Chroot environment?

Many thanks!!

**Comment by alkisg** [comment] 2019-09-13 12:40
wforumw, this issue is a duplicate of #16, let's continue there.

**Closed by alkisg** 2019-09-13 12:40 UTC
