### ISSUE TITLE
Failed to get global data

### ISSUE THREAD

**Issue by rkwesk** [ltsp/ltsp#31] opened 2019-09-19 20:10 UTC
Now in Debian Buster
```
root@ltsp19sonylap64:~# apt clean && apt update && apt -y full-upgrade && apt clean
The following packages will be upgraded:
  ltsp tzdata
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Get:1 http://deb.debian.org/debian buster-updates/main amd64 tzdata all 2019c-0+deb10u1 [261 kB]
Get:2 http://ppa.launchpad.net/ltsp/ppa/ubuntu bionic/main amd64 ltsp all 19.09-1~201909160643~ubuntu18.04.1 [66.3 kB]
```
So we are up to date.
Now, as you said to do:

```
root@ltsp19sonylap64:~# install -m 0660 /usr/share/ltsp/common/ltsp/ltsp.conf /etc/ltsp/.
root@ltsp19sonylap64:~# ltsp -o ipxe
Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipping existing /srv/tftp/ltsp/memtest.0
Skipping existing /srv/tftp/ltsp/memtest.efi
Skipping existing /srv/tftp/ltsp/snponly.efi
Skipping existing /srv/tftp/ltsp/undionly.kpxe
Installed iPXE binaries and configuration:
-rw-r--r-- 1 root root 2990 Sep 19 22:40 /srv/tftp/ltsp/ltsp.ipxe
-rw-r--r-- 1 root root 161968 Jul 24 13:10 /srv/tftp/ltsp/memtest.0
-rw-r--r-- 1 root root 1235864 Jul 24 13:10 /srv/tftp/ltsp/memtest.efi
-rw-r--r-- 1 root root 159296 Jul 24 13:10 /srv/tftp/ltsp/snponly.efi
-rw-r--r-- 1 root root 67642 Jul 24 13:10 /srv/tftp/ltsp/undionly.kpxe
```
Looks fine so far.
But when I tried this right afterwards:

```
root@ltsp19sonylap64:~# ltsp initrd && ltsp -o ipxe && ltsp -o dnsmasq d1 p0 && ltsp -o nfs
Generated ltsp.img:
-rw-r--r-- 1 root root 138752 Sep 19 22:41 /srv/tftp/ltsp/ltsp.img
Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipping existing /srv/tftp/ltsp/memtest.0
Skipping existing /srv/tftp/ltsp/memtest.efi
Skipping existing /srv/tftp/ltsp/snponly.efi
Skipping existing /srv/tftp/ltsp/undionly.kpxe
Installed iPXE binaries and configuration:
-rw-r--r-- 1 root root 2990 Sep 19 22:41 /srv/tftp/ltsp/ltsp.ipxe
-rw-r--r-- 1 root root 161968 Jul 24 13:10 /srv/tftp/ltsp/memtest.0
-rw-r--r-- 1 root root 1235864 Jul 24 13:10 /srv/tftp/ltsp/memtest.efi
-rw-r--r-- 1 root root 159296 Jul 24 13:10 /srv/tftp/ltsp/snponly.efi
-rw-r--r-- 1 root root 67642 Jul 24 13:10 /srv/tftp/ltsp/undionly.kpxe
Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found.
LTSP command failed: systemd-resolve --status
Installed /usr/share/ltsp/server/dnsmasq/ltsp-dnsmasq.conf in /etc/dnsmasq.d/ltsp-dnsmasq.conf
Restarted dnsmasq
Installed /usr/share/ltsp/server/nfs/ltsp-nfs.exports in /etc/exports.d/ltsp-nfs.exports
Restarted nfs-kernel-server
```

So the only difference this time is that I ran ltsp initrd before ltsp -o ipxe.
Now I'll post this and reboot into Ubuntu again and try the same thing there.

Richard

**Comment by rkwesk** [comment] 2019-09-19 20:38
Now in Ubuntu (same laptop, another partition)

Again getting upto date:

```
root@ltsp19:~# apt clean && apt update && apt -y full-upgrade && apt clean
The following packages will be upgraded:
  gnome-control-center-faces thermald
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Doing the same as I did in Debian:

root@ltsp19:~# install -m 0660 /usr/share/ltsp/common/ltsp/ltsp.conf /etc/ltsp/.
root@ltsp19:~# ltsp -o ipxe
Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipping existing /srv/tftp/ltsp/memtest.0
Skipping existing /srv/tftp/ltsp/memtest.efi
Skipping existing /srv/tftp/ltsp/snponly.efi
Skipping existing /srv/tftp/ltsp/undionly.kpxe
Installed iPXE binaries and configuration:
-rw-r--r-- 1 root root 2990 Σεπ  19 23:14 /srv/tftp/ltsp/ltsp.ipxe
-rw-r--r-- 1 root root 161968 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.0
-rw-r--r-- 1 root root 1235864 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.efi
-rw-r--r-- 1 root root 159296 Ιουλ 24 13:10 /srv/tftp/ltsp/snponly.efi
-rw-r--r-- 1 root root 67642 Ιουλ 24 13:10 /srv/tftp/ltsp/undionly.kpxe
```

No problem this first time just running ltsp -o ipxe, just as in Debian

AND no problem even when running ltsp initrd before ltsp -o ipxe

```
root@ltsp19:~# install -m 0660 /usr/share/ltsp/common/ltsp/ltsp.conf /etc/ltsp/.root@ltsp19:~# blkid /dev/sda7 >> /etc/fstab
root@ltsp19:~# ltsp initrd && ltsp -o ipxe && ltsp -o dnsmasq d1 p0 && ltsp -o nfs
Generated ltsp.img:
-rw-r--r-- 1 root root 139776 Σεπ  19 23:19 /srv/tftp/ltsp/ltsp.img
Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipping existing /srv/tftp/ltsp/memtest.0
Skipping existing /srv/tftp/ltsp/memtest.efi
Skipping existing /srv/tftp/ltsp/snponly.efi
Skipping existing /srv/tftp/ltsp/undionly.kpxe
Installed iPXE binaries and configuration:
-rw-r--r-- 1 root root 2990 Σεπ  19 23:19 /srv/tftp/ltsp/ltsp.ipxe
-rw-r--r-- 1 root root 161968 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.0
-rw-r--r-- 1 root root 1235864 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.efi
-rw-r--r-- 1 root root 159296 Ιουλ 24 13:10 /srv/tftp/ltsp/snponly.efi
-rw-r--r-- 1 root root 67642 Ιουλ 24 13:10 /srv/tftp/ltsp/undionly.kpxe
Installed /usr/share/ltsp/server/dnsmasq/ltsp-dnsmasq.conf in /etc/dnsmasq.d/ltsp-dnsmasq.conf
Restarted dnsmasq
Installed /usr/share/ltsp/server/nfs/ltsp-nfs.exports in /etc/exports.d/ltsp-nfs.exports
Restarted nfs-kernel-server
```

I'm out of ideas.

Richard

**Comment by alkisg** [comment] 2019-09-19 20:42
Richard I'm not sure what you're trying to do, and what the problem is.

The problem that you mention: "Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found."
...does not come from ltsp. It comes from the command `systemd-resolve --status`.

For some reason, you have a broken system, maybe misconfigured, maybe with missing dependencies due to a minimal installation or something, and while you have the `systemd-resolve` command there, it doesn't work properly.

LTSP does the correct thing there. It shows you the error that the command produced so that you know that you have a broken system, and then it ignores that error and continues with the next method of detecting the DNS servers, which is to parse /etc/resolv.conf directly.

So: LTSP works fine, and your system is misconfigured.
Am I missing anything?

**Comment by rkwesk** [comment] 2019-09-20 06:01
I understand what you are saying and thank you for your input. I will investigate further. I now regard this as a non-issue as far as ltsp19 is concerned.

Indeed my Debian is minimal. I think that both networkd-dispatcher and resolvconf are installed in the usual Ubuntu-Mate 18.04 but neither is installed in my Debian Buster/

```
rkwesk@ltsp19sonylap64:~$ dpkg -l | grep networkd-dispatcher
rkwesk@ltsp19sonylap64:~$ dpkg -l | grep resolvconf
```
The fact that my system reports "Unit dbus-org.freedesktop.resolve1.service not found" is perfectly understandable. What confuses me is that:

Apparently something triggers my system to check for Unit dbus-org.freedesktop.resolve1.service  when I run:

```
ltsp initrd && ltsp -o ipxe
~~~

but not when I run

```
ltsp -o ipxe
~~~

without "ltsp initrd

Richard

**Comment by alkisg** [comment] 2019-09-20 06:32
It's `ltsp dnsmasq` that runs `systemd-resolve --status`, not the other commands that you wrote.
You may also manually run `systemd-resolve --status` and reproduce the error without involving LTSP at all.

Closing as it's a problem of missing packages, and even so LTSP still manages to work correctly.

**Closed by alkisg** 2019-09-20 06:32 UTC

**Comment by rkwesk** [comment] 2019-09-21 12:51
I can confirm that although the error message is displayed. Indeed the client logs in and has Internet access.

Richard
