### ISSUE TITLE
LTSP fails to boot due to missing kernel

### ISSUE THREAD

**Issue by danboid** [ltsp/ltsp#152] opened 2020-09-14 16:16 UTC
I have just tried to set up a new LTSP server based upon Ubuntu MATE 20.04 amd64 by following the instructions here https://ltsp.org/docs/installation/

Everything seemed to be going fine until I ran `ltsp image /` when I got the following error at the end of building the LTSP image:

```
Could not locate vmlinuz and initrd.img in /srv/ltsp/images/x86_64.img
```
There are indeed no files in /srv/ltsp (apart from the images dir) after following the installation guide in full.

When I try to boot from LTSP I get the error:

```
/ltsp/x86_64/vmlinuz... No such file or directory
```
I wonder if this is related to me installing with ZFS root?

**Comment by alkisg** [comment] 2020-09-14 17:13
Duplicate of #43

**Closed by alkisg** 2020-09-14 17:13 UTC

**Comment by danboid** [comment] 2020-09-14 22:17
After looking at #43 I ran:

```
mount --bind / /mnt
cp -a /boot/. /mnt/boot/
umount /mnt
```

and that has fixed the missing kernel problem at least.

The problem here though is that #43 was closed almost a year ago but the problem persists in the latest PPA version of LTSP. If this can't be fixed then shouldn't these extra steps be mentioned in the installation guide?

**Comment by alkisg** [comment] 2020-09-15 04:18
Hi danboid,

it's best to continue discussion in #43, not here. Copy/paste your question there and I'll answer it there.
