### ISSUE TITLE
Can't boot raspberry pi with custom base-dir/tftp-dir

### ISSUE THREAD

**Issue by bbinet** [ltsp/ltsp#485] opened 2021-06-29 21:39 UTC
I need to customize base-dir (defaults to /srv/ltsp) and tftp-dir (defaults to /srv/tftp), but when I do so, the raspberry pi fails to boot.
This seems to be caused by hardcoded values ["/srv/ltsp" here](https://github.com/ltsp/ltsp/blob/main/ltsp/client/init/25-ro-root.sh#L30) and ["/srv/tftp" here](https://github.com/ltsp/ltsp/blob/main/ltsp/client/init/25-ro-root.sh#L46).
If I make a dirty patch to hardcode new values that match my custom base-dir/tftp-dir locations, the raspberry pi boots successfully.

What would be the correct way to fix this?
Would it be possible to replace these hardcoded values by corresponding base-dir/tftp-dir settings?

**Comment by alkisg** [comment] 2021-06-30 03:26
At that point (25-ro-root) the client only has a read only NFS root mounted. The ltsp.conf settings from ltsp.img aren't available yet.

Nevertheless, it should be possible to set BASE_DIR in /srv/ltsp/raspios/etc/ltsp/ltsp.conf (or any other location you're using) and it would be sourced.

So yeah a patch should be possible, thank you for reporting this.
Unfortunately, it'll need to wait until the next big LTSP version, in time for Ubuntu 22.04.

**Comment by bbinet** [comment] 2021-06-30 07:40
Ok, thank you for your reply.

So you mean it won't be available before April 2022?
Can't we plan to make minor updates until then for bugfixes or small improvements?

**Comment by alkisg** [comment] 2021-06-30 08:13
The problem is that some "less important" changes may cause bugs elsewhere.
A proper LTSP release requires e.g. a week of testing.
I can only do such big testing sparingly, and I align it before Debian or Ubuntu LTS releases.

But in the meantime, there are some "more important" (or more innocent) changes that deserve to be released, first in the proposed PPA and sometimes in the stable PPA afterwards.
For this to work, the "upstream development tree" must not contain any "less important", untested changes.

So, the merge period for the "less important" changes are before the big testing periods, i.e. before Debian/Ubuntu LTS releases.

In the meantime, you may submit a patch, I can review it and say "it looks good", and you can apply it in your local LTSP code, without waiting for an LTSP release that contains it.

**Comment by bbinet** [comment] 2021-06-30 14:53
I see, it sounds good.
Hopefully, Debian Bullseye might be released before Ubuntu 22.04 ;-)

I may be able to submit a pull request. Something like that would be ok? (not tested yet)

``` patch
diff --git a/ltsp/client/init/25-ro-root.sh b/ltsp/client/init/25-ro-root.sh
index 47340ca..0f81ed5 100644
--- a/ltsp/client/init/25-ro-root.sh
+++ b/ltsp/client/init/25-ro-root.sh
@@ -27,7 +27,7 @@ ro_root_main() {
         # We want an existing mount point for the tmpfs outside of /run,
         # otherwise switch_root can't move the /run mount as it's in use.
         # Let's use /root that is used by initramfs-tools and always exists.
-        re vmount -t nfs -o vers=3,nolock "$SERVER:/srv/ltsp" /root
+        re vmount -t nfs -o vers=3,nolock "$SERVER:${SERVER_BASE_DIR:-/srv/ltsp}" /root
         re vmount -o loop,ro "/root/$IMAGE" /root
         re mount_img_src /root /root /run/initramfs/ltsp
     else
@@ -43,7 +43,7 @@ ro_root_main() {
 fetch_ltsp_img() {
     re mkdir -p /run/ltsp/tmp/tftp
     re vmount --no-exit -t nfs -o vers=3,tcp,nolock \
-        "$SERVER:/srv/tftp/ltsp" /run/ltsp/tmp/tftp
+        "$SERVER:${SERVER_TFTP_DIR:-/srv/tftp}/ltsp" /run/ltsp/tmp/tftp
     re test -f /run/ltsp/tmp/tftp/ltsp.img
     re mkdir -p /run/ltsp/tmp/ltsp-img
     (
```

**Comment by alkisg** [comment] 2021-06-30 15:20
Use BASE_DIR and TFTP_DIR, without SERVER there. Their definitions are in:

```shell
$ grep -A2 /srv/ltsp /usr/share/ltsp/ltsp/common/ltsp/55-ltsp.sh
BASE_DIR=${BASE_DIR:-/srv/ltsp}
TFTP_DIR=${TFTP_DIR:-/srv/tftp}
HOME_DIR=${HOME_DIR:-/home}
```

The LTSP 21.01 version for Debian Bullseye was released in January 2021:
https://packages.debian.org/bullseye/ltsp

While LTSP 22.01 for Ubuntu 22.04 will be released in January 2022.

**Comment by bbinet** [comment] 2021-06-30 16:17
Ok, but BASE_DIR/TFTP_DIR on the client can be different from those of the server, no?
From [your first comment](https://github.com/ltsp/ltsp/issues/485#issuecomment-871068204), I've understand that I need to set custom base-dir/tftp-dir variables in the /etc/ltsp/ltsp.conf file of my chroot, right?
So I thought that using BASE_DIR in /etc/ltsp/ltsp.conf in the chroot would set the actual BASE_DIR of the client, and I supposed it could generate issues if the ltsp client also makes use of BASE_DIR. Is BASE_DIR  a server variable only?
So that's why I had opted for SERVER_BASE_DIR in the first place.

If it's safe to use BASE_DIR/TFTP_DIR, then the patch would look like the following, right?
``` patch
diff --git a/ltsp/client/init/25-ro-root.sh b/ltsp/client/init/25-ro-root.sh
index 0f81ed5..137a5bf 100644
--- a/ltsp/client/init/25-ro-root.sh
+++ b/ltsp/client/init/25-ro-root.sh
@@ -27,7 +27,7 @@ ro_root_main() {
         # We want an existing mount point for the tmpfs outside of /run,
         # otherwise switch_root can't move the /run mount as it's in use.
         # Let's use /root that is used by initramfs-tools and always exists.
-        re vmount -t nfs -o vers=3,nolock "$SERVER:${SERVER_BASE_DIR:-/srv/ltsp}" /root
+        re vmount -t nfs -o vers=3,nolock "$SERVER:${BASE_DIR:-/srv/ltsp}" /root
         re vmount -o loop,ro "/root/$IMAGE" /root
         re mount_img_src /root /root /run/initramfs/ltsp
     else
@@ -43,7 +43,7 @@ ro_root_main() {
 fetch_ltsp_img() {
     re mkdir -p /run/ltsp/tmp/tftp
     re vmount --no-exit -t nfs -o vers=3,tcp,nolock \
-        "$SERVER:${SERVER_TFTP_DIR:-/srv/tftp}/ltsp" /run/ltsp/tmp/tftp
+        "$SERVER:${TFTP_DIR:-/srv/tftp}/ltsp" /run/ltsp/tmp/tftp
     re test -f /run/ltsp/tmp/tftp/ltsp.img
     re mkdir -p /run/ltsp/tmp/ltsp-img
     (
```

**Comment by alkisg** [comment] 2021-06-30 16:20
Yes that patch looks good.
If there's ever any need to set a different BASE_DIR on the client vs the server, one can use the [clients] and [server] sections in ltsp.conf.

Both the server and the clients read the server's /etc/ltsp/ltsp.conf.
But especially 25-ro-root.sh reads $CHROOT/etc/ltsp/ltsp.conf. Nothing else reads that one though, it's not used in normal LTSP, it's only for Raspberries that don't use an initramfs.

**Comment by bbinet** [comment] 2021-06-30 16:35
Ok, great, thank you.
See PR #486

**Closed** 2021-10-11 05:31 UTC
