### ISSUE TITLE
Ubuntu problem but Debian success on same pc's 2 nics

### ISSUE THREAD

**Issue by rkwesk** [ltsp/ltsp#24] opened 2019-09-05 20:34 UTC
This same laptop with lan on onboard nic and wan on wireless had just succeeded with Debian Buster mate to have one client ltsp10.
On another partition Ubuntu mate 18.04.3 also updated with latest ltsp and other pkgs and recreating the image and running ltsp initrd and rebooted (just to be sure) didnot succeed to get the same client to boot.

'''root@ltsp19:~# ltsp info'''
LTSP version: 19.09-1~201909021800~ubuntu18.04.1

SERVER XSESSIONS: mate.desktop

SERVER OS: PRETTY_NAME="Ubuntu 18.04.3 LTS"

CHROOTS:

VMs:

IMAGES:
x86_64

'''root@ltsp19:~# lspci | grep Ethernet'''
02:00.0 Ethernet controller: Marvell Technology Group Ltd. 88E8039 PCI-E Fast Ethernet Controller (rev 15)
06:00.0 Ethernet controller: Qualcomm Atheros AR242x / AR542x Wireless Network Adapter (PCI-Express) (rev 01)

'''root@ltsp19:~# ip a'''
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1a:80:b5:a7:e7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.67.1/24 brd 192.168.67.255 scope global noprefixroute enp2s0
       valid_lft forever preferred_lft forever
    inet6 fe80::4f32:eff2:a02c:8306/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1d:d9:7b:0a:6d brd ff:ff:ff:ff:ff:ff
    inet 10.72.251.202/24 brd 10.72.251.255 scope global dynamic noprefixroute wlp6s0
       valid_lft 1806852sec preferred_lft 1806852sec
    inet6 2a02:587:2d24:1900:e109:6dca:15d8:dde5/64 scope global temporary dynamic 
       valid_lft 58723sec preferred_lft 58723sec
    inet6 2a02:587:2d24:1900:574:f723:7d9b:e87a/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 58723sec preferred_lft 58723sec
    inet6 fe80::cdf9:ca31:ab4a:a89f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

Messages from the client and the server:

On client side

iPXE 1.0.0+ (a4f8) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT

net0: 00:1e:8c:16:54:1a using undionly on 0000:01:00.0 (open)
   [Link:up, TX:0 TXE:1 RX:0 RXE:0]
   [TXE: 1 x "Network unreachable (http://ipxe.org/28086011)"]
Configuring (net0 00:1e:8c:16:54:1a)... ok
net0: 192.168.67.214/255.255.255.0 gw 192.168.67.1
Next server: 192.168.67.1
Filename: ltsp/ltsp.ipxe
tftp://192.168.67.1/ltsp/ltsp.ipxe... ok
ltsp.ipxe : 2987 bytes [script]
Could not boot image: Result too large (http://ipxe.org/46022001)
No more network devices

On server side

'''root@ltsp19:~# tail -f /var/log/syslog'''

Sep  5 23:14:43 ltsp19 dnsmasq-dhcp[726]: DHCPDISCOVER(enp2s0) 00:1e:8c:16:54:1a
Sep  5 23:14:43 ltsp19 dnsmasq-dhcp[726]: DHCPOFFER(enp2s0) 192.168.67.214 00:1e:8c:16:54:1a
Sep  5 23:14:45 ltsp19 dnsmasq-dhcp[726]: DHCPREQUEST(enp2s0) 192.168.67.214 00:1e:8c:16:54:1a
Sep  5 23:14:45 ltsp19 dnsmasq-dhcp[726]: DHCPACK(enp2s0) 192.168.67.214 00:1e:8c:16:54:1a
Sep  5 23:14:45 ltsp19 dnsmasq-tftp[726]: error 0 TFTP Aborted received from 192.168.67.214
Sep  5 23:14:45 ltsp19 dnsmasq-tftp[726]: failed sending /srv/tftp/ltsp/undionly.kpxe to 192.168.67.214
Sep  5 23:14:45 ltsp19 dnsmasq-tftp[726]: sent /srv/tftp/ltsp/undionly.kpxe to 192.168.67.214
Sep  5 23:14:47 ltsp19 dnsmasq-dhcp[726]: DHCPDISCOVER(enp2s0) 00:1e:8c:16:54:1a
Sep  5 23:14:47 ltsp19 dnsmasq-dhcp[726]: DHCPOFFER(enp2s0) 192.168.67.214 00:1e:8c:16:54:1a
Sep  5 23:14:47 ltsp19 dnsmasq-dhcp[726]: DHCPREQUEST(enp2s0) 192.168.67.214 00:1e:8c:16:54:1a
Sep  5 23:14:47 ltsp19 dnsmasq-dhcp[726]: DHCPACK(enp2s0) 192.168.67.214 00:1e:8c:16:54:1a
Sep  5 23:14:47 ltsp19 dnsmasq-tftp[726]: sent /srv/tftp/ltsp/ltsp.ipxe to 192.168.67.214

Richard

**Comment by alkisg** [comment] 2019-09-06 01:00
I think this is a duplicate of issue #21, see https://github.com/ltsp/ltsp/issues/21#issuecomment-527212422

**Closed by alkisg** 2019-09-06 01:00 UTC

**Comment by alkisg** [comment] 2019-09-06 02:50
Richard, to be clear,
this problem started 4 days ago,
and got solved 3 days ago,
and `apt full-upgrade; ltsp -o ipxe` was needed to apply the new code/solution.

I.e. it's not related to the distribution that you used, just to the timing of the testing.

**Comment by rkwesk** [comment] 2019-09-06 08:18
Thank you Alki. I applied it and it fixed it. However, when I try to follow the commentary in the terminal it seemed that the overwrite was not being done - which, of course, was not true since it got fixed!
'''root@ltsp19:~# ltsp -o ipxe''' 
/usr/sbin/ltsp: 96: /usr/sbin/ltsp: section_list: not found

Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipping existing /srv/tftp/ltsp/memtest.0
Skipping existing /srv/tftp/ltsp/memtest.efi
Skipping existing /srv/tftp/ltsp/snponly.efi
Skipping existing /srv/tftp/ltsp/undionly.kpxe
Installed iPXE binaries and configuration:
-rw-r--r-- 1 root root 2990 Σεπ   6 10:09 /srv/tftp/ltsp/ltsp.ipxe
-rw-r--r-- 1 root root 161968 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.0
-rw-r--r-- 1 root root 1235864 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.efi
-rw-r--r-- 1 root root 159296 Ιουλ 24 13:10 /srv/tftp/ltsp/snponly.efi
-rw-r--r-- 1 root root 67642 Ιουλ 24 13:10 /srv/tftp/ltsp/undionly.kpxe
I don't follow the issues every day and often miss what is said. For example I go to search for the issue in which ltsp -o ipxe and I don't see it. :((
Richard
    On Friday, September 6, 2019, 2:50:20 AM UTC, Alkis Georgopoulos <notifications@github.com> wrote:  
 
 
Richard, to be clear,
this problem started 4 days ago,
and got solved 3 days ago,
and apt full-upgrade; ltsp -o ipxe was needed to apply the new code/solution.

I.e. it's not related to the distribution that you used, just to the timing of the testing.

**Comment by alkisg** [comment] 2019-09-06 08:29
> I don't follow the issues every day and often miss what is said. For example I go to search for the issue in which ltsp -o ipxe and I don't see it. :((

Hi Richard,

to see the LTSP issues, you go there:
https://github.com/ltsp/ltsp/issues

Note that there, you'll only see the "Open" issues. If I closed an issue because I think it was resolved, you'll need to click on the "[Closed](https://github.com/ltsp/ltsp/issues?q=is%3Aissue+is%3Aclosed)" option in that web page.

Of course if the issue wasn't resolved for you, you can still comment in it and ask/give feedback even if I closed it.

Also note that to write shell code or shell output in github, it's best to use three backticks, like this:

\`\`\`
Code or output goes here
\`\`\`

This tells github not to avoid parsing the shell output as markdown.
